# Generated by Django 3.1.1 on 2020-09-20 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astrogaming_apis', '0005_screenshots'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Screenshots',
            new_name='ScreenshotsModels',
        ),
    ]
